id: I4D74037A
legacy_id: P000388
ocr_import_info:
  bdrc_scan_id: W1KG5786
  source: bdrc
  ocr_info:
    timestamp: '2020-03-17T14:09:32'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:25:07.839655+00:00'
last_modified: 2022-09-01 01:25:19.751766
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5786
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5786
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ནི་གུའི་ཆོས་དྲུག་གྲུབ་པའི་དགོངས་རྒྱན།
  author: དངོས་གྲུབ་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.9649801443464682
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG5822:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5822
      total_pages: 312
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5822.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9649801443464682
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
