id: P000388
initial_creation_type: ocr
created_at: 17/03/2020
last_modified_at: 2021-12-16 15:37:22.990209
source_metadata:
  id: bdr:W1KG5786
  title: ནི་གུའི་ཆོས་དྲུག་གྲུབ་པའི་དགོངས་རྒྱན་
  author: ''
  volumes:
    746f554833614ea89a9c80fb09e6c0a5:
      image_group_id: I1KG5822
      title: Volume 1 of ni gu'i chos drug grub pa'i dgongs rgyan
      volume_number: 1
      total_pages: 312
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
